### ISSUE TITLE
output sketch problem

### ISSUE THREAD

**Issue by Cvar1984** [shvelo/arduino-music#1]
town.ino:17:1: error: duplicate ‘const’
 const unsigned char PROGMEM score [] = {
 ^
town.ino: In function ‘void loop()’:
town.ino:184:27: error: invalid conversion from ‘const unsigned char*’ to ‘byte* {aka unsigned char*}’ [-fpermissive]
   pt.tune_playscore (score);  /* start playing */
                           ^
In file included from town.ino:13:0:
/usr/share/arduino/libraries/Playtune/Playtune.h:43:7: note: initializing argument 1 of ‘void Playtune::tune_playscore(byte*)’
  void tune_playscore (byte *score);  // start playing a polyphonic score
       ^
/usr/share/arduino/Arduino.mk:1215: recipe for target 'build-uno/town.o' failed
make: *** [build-uno/town.o] Error 1

https://pastebin.com/JdRW30s0

**Comment by shvelo** [comment]
Should be fixed now, pull and don't forget to run `git submodule update --init`
